version: '3'

services:
    api:
        build: .
        restart: unless-stopped
        depends_on:
            - database
        ports:
            - '8000:8080'
        environment:
            - PORT=8080
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
            - POSTGRES_HOST=database
            - POSTGRES_PORT=5432

    database:
        image: postgres:12
        restart: unless-stopped
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB