version: '3'

services:
    api:
        image: api
        restart: unless-stopped
        command: ['/bin/sh', '-c', 'while ! pg_isready -h $${POSTGRES_HOST} -p $${POSTGRES_PORT} -U $${POSTGRES_USER}; do sleep 5; done && ./airquality']
        depends_on:
            - database
            - setup
        ports:
            - '8000:8080'
        environment:
            - PORT=8080
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
            - POSTGRES_HOST=database
            - POSTGRES_PORT=5432
            - GIN_MODE

    database:
        image: postgres:12
        restart: unless-stopped
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB

    setup:
        build: .
        image: api
        command: ['/bin/sh', '-c', 'while ! pg_isready -h $${POSTGRES_HOST} -p $${POSTGRES_PORT} -U $${POSTGRES_USER}; do sleep 5; done && ./airquality /data.csv']
        depends_on: 
            - database
        volumes: 
            - ${PWD}/environment_airq_measurand.csv:/data.csv:ro # set to the desired file to import
        environment:
            - PORT=8080
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
            - POSTGRES_HOST=database
            - POSTGRES_PORT=5432