apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.kubernetes.yml
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: database
  name: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: database
status:
  loadBalancer: {}
