apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # api
  - api-deployment.yaml
  - api-service.yaml
  # database
  - database-deployment.yaml
  - database-service.yaml
  - dbdata-persistentvolumeclaim.yaml
  # cache
  - varnish-statefulset.yaml
  - varnish-configmap.yaml
  - varnish-service.yaml
  # secrets
  - secret.yaml

namespace: default
