apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
data:
  POSTGRES_USER: YWlycXVhbGl0eQ==
  POSTGRES_PASSWORD: YWlycXVhbGl0eVN1cGVyU2VxdXJlUGFzc3dvcmQ=

---
apiVersion: v1
kind: Secret
metadata:
  name: varnish-secret
data:
  secret: rn0s8MczddElto3M2qEUELQQoYrVvc4k+WfvtYmLjc8=
